# Generated by Django 5.2.8 on 2025-12-02 02:07

import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_description', models.CharField(default='', max_length=100)),
                ('transaction_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('transaction_type', models.CharField(choices=[('income', 'Income Transaction'), ('outcome', 'Outcome Transaction')], max_length=50)),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
