# Generated by Django 5.2.8 on 2025-12-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_transaction_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'Income Transaction'), ('expense', 'Expense Transaction')], default='income', max_length=50),
        ),
    ]
