# Generated by Django 5.2.8 on 2025-12-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0003_rename_transaction_amount_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'Income Transaction'), ('expense', 'Expense Transaction')], max_length=50),
        ),
    ]
